### PR TITLE
Rewordings & rearrangings

### PR DESCRIPTION
**Pull request by ozh**
First commit about the `/guide` section, second will cover the `/development` one

### CODE REVIEW

**Comment by ozh** [comment]
@LeoColomb I don't know what the problem is and how I can double check things on my end.

Here's the result on my box, there's basically a warn on every file including those I haven't touched yet.
```
$ npm run lint

> @ lint D:\home\planetozh\YOURLS-docs
> prettier --check .

Checking formatting...
[warn] .github\dependabot.yml
[warn] .github\ISSUE_TEMPLATE\config.yml
[warn] .github\workflows\auto-merge.yml
[warn] .github\workflows\lint.yml
[warn] .prettierrc
[warn] .vitepress\config.ts
[warn] .vitepress\config\navbar.ts
[warn] .vitepress\config\sidebar.ts
[warn] .vitepress\theme\components\Home.vue
[warn] .vitepress\theme\index.ts
[warn] .vitepress\theme\styles\styles.css
[warn] env.d.ts
[warn] package-lock.json
[warn] package.json
[warn] README.md
[warn] src\development\coding-standards.md
[warn] src\development\database-queries.md
[warn] src\development\debugging.md
[warn] src\development\dont-hack-core.md
[warn] src\development\examples\preview.md
[warn] src\development\examples\public-prefix.md
[warn] src\development\examples\qrcode.md
[warn] src\development\examples\rss.md
[warn] src\development\hooks.md
[warn] src\development\i18n.md
[warn] src\development\plugins.md
[warn] src\guide\advanced\custom-protocols.md
[warn] src\guide\advanced\passwordless-api.md
[warn] src\guide\advanced\proxy.md
[warn] src\guide\advanced\public-shortening.md
[warn] src\guide\essentials\charset.md
[warn] src\guide\essentials\configuration.md
[warn] src\guide\essentials\credentials.md
[warn] src\guide\essentials\private-or-public.md
[warn] src\guide\extend\languages.md
[warn] src\guide\extend\pages.md
[warn] src\guide\extend\plugins.md
[warn] src\guide\extend\possible-with-a-plugin.md
[warn] src\guide\install.md
[warn] src\guide\introduction.md
[warn] src\guide\server-configuration.md
[warn] src\guide\troubleshooting\abuse.md
[warn] src\guide\troubleshooting\first-steps.md
[warn] src\guide\troubleshooting\frequent-issues.md
[warn] src\index.md
[warn] src\sponsor.md
[warn] tsconfig.json
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lint: `prettier --check .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     path\npm-cache\_logs\2022-04-03T16_08_26_044Z-debug.log
```

(last file being useless to diagnose the problem it seems)

**Comment by ozh** [comment]
My 2 cents : we definitely don't care about this kind of linting, especially if there is no explanation in Github actions result.

Checking for broken links, yes. Nitpicking about an extra empty line on a markdown file, no.

**Comment by ozh** [comment]
If nobody minds I'll enable the "squash and merge right now without waiting for a review" like on YOURLS/YOURLS

**Comment by LeoColomb** [comment]
@ozh Why did you merged? 😱

**Comment by ozh** [comment]
Errr because it was all fine ? :)

**Comment by LeoColomb** [comment]
> If nobody minds I'll enable the "squash and merge right now without waiting for a review"

I do mind! Just to let me time to breath during the weekend and keep me healthy without having to rush review. 😅

**Comment by LeoColomb** [comment]
> Errr because it was all fine ? :)

How do you know? Someone have made a review?

**Comment by ozh** [comment]
I won't squash PR that change the core of things, ie theming, settings, whatever.

For the content itself, I can judge if it's suitable (and anyone of us can), just like we ran things so far on YOURLS/YOURLS/wiki, or just like I'll approve the PR of some contributor without waiting for another admin to approve

**Comment by dgw** [comment]
> or just like I'll approve the PR of some contributor without waiting for another admin to approve

I think you meant "merge the PR of" here?

> For the content itself, I can judge if it's suitable (and anyone of us can), just like we ran things so far on YOURLS/YOURLS/wiki

It's not the same when you're looking at a patch your wrote yourself. You must see that Léo has a point in this case—in fact if we used GitHub's require-approval system, you'd notice that it very smartly will not let you approve your own PR to prevent conflict of interest.

**Comment by dgw** [comment]
Let's not compare these docs to those for a YOURLS version that isn't even released yet :)

Anyway, I have no skin in this game—just wanted to point out why @LeoColomb might be frustrated, and that blocking people from unilaterally approving their own stuff is built into the tools here _if_ we used those features.

FWIW, I'm used to seeking review approval even for trivial typo fixes, because that's just how the other project I spend the most time on works. But it's also true that we enforce no such required-review policy on the website repo, because the reviews would never happen. Contributors focus on our (bundled) Sphinx docs, and it shows. 😂😅

**Pull request merged**
