### PR TITLE
Document PHP extension requirements (sort of)

### PR DESCRIPTION
**Pull request by dgw**
Might have prevented YOURLS/YOURLS#3337

### CODE REVIEW

**Review by ozh — COMMENTED** [review]
This is a very default extension and so far there has been only one issue about this. There are a lot of default extensions that YOURLS needs (hash, PDO, json...) and that would be maybe overkill to list them all (and maybe letting noob users think YOURLS requires an awful lot of custom stuff). Thoughts?

**Comment by dgw** [comment]
Maybe this exact page/bullet-point is the wrong place for such a list, but I'd say that the required extensions should be listed _somewhere_ in the documentation for reference.

**Comment by ozh** [comment]
Nothing against it, but I don't know how to generate a list of needed default extensions ...

**Comment by dgw** [comment]
I took a quick trip to google and found that [Composer might be able](https://blog.digital-craftsman.de/check-php-extensions-requirement-with-composer/) to do it (`composer check-platform-reqs`). And it does work on my local checkout, but doesn't appear to show all used extensions. It doesn't even list `ext-mbstring`, [which is suggested](https://github.com/YOURLS/YOURLS/blob/7fdde60aa6668cb73d121cc7c48ca8c6f7acacae/composer.json#L43) in YOURLS' own composer.json—but it _does_ show `ext-curl`.

Maybe this is a half-baked Composer feature? The result didn't change after `composer self-update` to 2.3.5.

As an alternative I tried out https://github.com/RogerGee/php-ext-depends, with a better (but still seemingly incomplete) result:

```
~/github/php-ext-depends$ php depends.php --suffix .php ../YOURLS
Core (builtin)
ctype
curl
date (builtin)
dom
filter
hash
iconv
json
mbstring
openssl
pcre (builtin)
PDO
posix
SPL (builtin)
standard (builtin)
zlib
```

Still, this should be most of what's required. Amendments can be made if users find something that isn't listed causes an error when missing.

(Also I _just_ noticed that my branch name is wrong. How did I get an `=`? No idea.)

**Comment by ozh** [comment]
This list isn't accurate either. For instance, `iconv` is not required, see https://github.com/YOURLS/YOURLS/blob/master/includes/functions-formatting.php#L328-L331

I would suggest we 

* add all the extension requirements / suggestions in YOURLS/YOURLS composer.json for reference
* only list on docs.yourls.org the common requirements as currently
* and mention on docs.yourls.org that common extensions needed are listed in the composer.json for those dealing with uncommon setups

Emphasis on "for 99.9% of folks we just need standard stuff"

**Comment by ozh** [comment]
Regarding the specific case of mysqlnd, I think it's de facto covered by the ["ext-pdo": "*",](https://github.com/YOURLS/YOURLS/blob/master/composer.json#L20) we already have

**Comment by dgw** [comment]
Ah well, the readme for php-ext-depends specifically says that it doesn't try to determine if use of an extension function is in an optional code path.

I went through the previous list real quick and annotated things as best I could:

- runtime use
  - curl (optional, already documented)
  - dom (used by spatie/array-to-xml)
  - filter ([in Composer class loader](https://github.com/YOURLS/YOURLS/blob/e05ee2aefb5b8c021da2b3a23aa488109315b1a1/includes/vendor/composer/ClassLoader.php#L369), but I'm not 100% sure when/if this runs)
  - hash
  - iconv (optional; [used if present](https://github.com/YOURLS/YOURLS/blob/7fdde60aa6668cb73d121cc7c48ca8c6f7acacae/includes/functions-formatting.php?rgh-link-date=2022-05-15T14%3A31%3A34Z#L328-L331))
  - json ([maybe optional?](https://github.com/YOURLS/YOURLS/blob/23d21fd996e771c4015f5d8b4ec1b06af122d60b/includes/functions-compat.php#L13-L17))
  - mbstring (optional; [used if present](https://github.com/YOURLS/YOURLS/blob/2edfa136e19c5aa75be0a812f7e5bd82be7f6aef/includes/functions.php#L911))
  - openssl ([basically optional](https://github.com/YOURLS/YOURLS/blob/6da30dfab08700888d4403a8ce2abaaf47ec11c7/includes/functions-http.php#L524))
  - PDO w/MySQL driver(s)
  - posix (but maybe unused? [polyfill](https://github.com/YOURLS/YOURLS/blob/007882fac0a7b55a9b289826c65b2ffabaa8a758/includes/vendor/symfony/polyfill-php72/Php72.php#L148))
  - zlib (part of [Requests](https://github.com/YOURLS/YOURLS/blob/e05ee2aefb5b8c021da2b3a23aa488109315b1a1/includes/vendor/rmccue/requests/src/Requests.php#L917))
- tests only
  - ctype

If my conclusions are reasonable, I'd happily take a stab at updating composer.json with this info. Later I can change this docs PR to point to said updated file for more details.

**Comment by ozh** [comment]
👍

**Comment by LeoColomb** [comment]
👍 for this complete list!

**Comment by dgw** [comment]
Updated this to how it might look when pointing to `composer.json`. Of course the file doesn't have all the extensions listed yet. I'm working on that. Expect a PR to main repo tomorrow. 😸

**Comment by dgw** [comment]
And there we go: YOURLS/YOURLS#3339

**Review by ozh — APPROVED** [review]

**Pull request merged**
